&copy; 2020<br><br>
Oleh:<br><br>
Sandy Hardian Susanto Herho<br>
[sandyherho@protonmail.ch](mailto:sandyherho@protonmail.ch)<br><br>
Dasapta Erwin Irawan<br>
[r-win@office.itb.ac.id](mailto:r-win@office.itb.ac.id)

# Dasar - dasar pemrograman

## Aritmatika

In [1]:
1 + 2

[1] 3

In [2]:
5 - 3

[1] 2

In [3]:
5.25 + 3.95

[1] 9.2

In [4]:
3 * 2

[1] 6

In [5]:
15 / 2

[1] 7.5

In [6]:
2 ^ 3

[1] 8

In [7]:
# operator modulus

15/2 

[1] 7.5

In [8]:
15 %% 2

[1] 1

In [9]:
# urutan operasi
15 * 20 + 50 / 2

[1] 325

In [10]:
15 * 20 + (50 / 2)

[1] 325

In [11]:
15 * (20 + 50) / 2

[1] 525

## Variabel

In [12]:
# komentar
v <- 10

In [13]:
print(v)

[1] 10


In [14]:
v

[1] 10

In [15]:
uang <- 100000

In [16]:
uang

[1] 1e+05

In [17]:
tiket.bioskop <- 2e5 # paling sering digunakan di komunitas R
tiket.bioskop

[1] 2e+05

In [18]:
tiketBioskop <- 2.05e5
tiketBioskop

[1] 205000

In [19]:
tiket_bioskop <-2.1e5
tiket_bioskop

[1] 210000

In [20]:
popcorn <- 5e4
popcorn

[1] 50000

In [21]:
tiket.bioskop <- tiket.bioskop + popcorn + 2e4
print(tiket.bioskop)

[1] 270000


## Tipe - tipe data

### Numerik

In [22]:
b <- 2
b

[1] 2

In [23]:
d <- 3.5
d

[1] 3.5

In [24]:
class(d)

[1] "numeric"

In [25]:
class(b)

[1] "numeric"

Integer dan float di R dianggap sebagai tipe data numerik

### Logical

In [26]:
TRUE

[1] TRUE

In [27]:
FALSE

[1] FALSE

In [28]:
T

[1] TRUE

In [29]:
F

[1] FALSE

In [30]:
a <- TRUE
a

[1] TRUE

In [31]:
class(a)

[1] "logical"

### Character

In [32]:
"Halo"

[1] "Halo"

In [33]:
'Halo'

[1] "Halo"

In [34]:
txt <- "Hello world!"
print(txt)

[1] "Hello world!"


In [35]:
class(txt)

[1] "character"

## Vektor

In [36]:
num <- c(1,2,3,4,5)

In [37]:
class(num)

[1] "numeric"

In [38]:
txt <- c('a', 'b', 'c')
txt

[1] "a" "b" "c"

In [39]:
class(txt)

[1] "character"

In [40]:
l <- c(T,F)
l

[1]  TRUE FALSE

In [41]:
class(l)

[1] "logical"

In [42]:
v1 <- c(TRUE, 10, 20)
v1

[1]  1 10 20

In [43]:
class(v1) # logical dikonversi menjadi numeric

[1] "numeric"

In [44]:
v2 <- c('a', 'b', 20)
v2

[1] "a"  "b"  "20"

In [45]:
class(v2) # numeric dikonversi menjadi character

[1] "character"

In [46]:
v3 <- c(TRUE, 128, 'Meteorologi')
v3

[1] "TRUE"        "128"         "Meteorologi"

In [47]:
class(v3) # logical & numeric dikonversi menjadi character

[1] "character"

In [48]:
# names : metode penamaaan vektor (metode 1) 
hari <- c(1,2,3,4,5,6,7)
hari

[1] 1 2 3 4 5 6 7

In [49]:
names(hari) <- c('sen', 'sel', 'rab', 'kam', 'jum', 'sab', 'min')

In [50]:
hari

sen sel rab kam jum sab min 
  1   2   3   4   5   6   7

In [51]:
# names : metode penamaaan vektor (metode 2)
b <-  c('sen', 'sel', 'rab', 'kam', 'jum', 'sab', 'min')
names(hari) <- b
hari

sen sel rab kam jum sab min 
  1   2   3   4   5   6   7

In [52]:
hari['sen']

sen 
  1

In [53]:
hari[1]

sen 
  1

## Operasi - operasi vektor

In [54]:
v1 <- c(1,2,3,4,5)
v2 <- c(6,7,8,9,10)

In [55]:
v1 + v2 # element-by-element

[1]  7  9 11 13 15

In [56]:
v1 - v2

[1] -5 -5 -5 -5 -5

In [57]:
v1 * v2

[1]  6 14 24 36 50

In [58]:
v2 / v2

[1] 1 1 1 1 1

In [59]:
sum(v1) # jumlah seluruh v1

[1] 15

In [60]:
mean(v1) # rata2 v1

[1] 3

In [61]:
sd(v1) # std v1

[1] 1.581139

In [62]:
max(v2)

[1] 10

In [63]:
min(v2)

[1] 6

In [64]:
prod(v1) # mengalikan seluruh elemen di vektor 

[1] 120

In [65]:
prod(v2)

[1] 30240

In [66]:
b <- sum(v1)
print(b)

[1] 15


## Operator - operator perbandingan

In [67]:
4 > 5

[1] FALSE

In [68]:
7 > 4

[1] TRUE

In [69]:
10 >= 5

[1] TRUE

In [70]:
7 <= 5

[1] FALSE

In [71]:
8 == 8

[1] TRUE

In [72]:
7 != 15

[1] TRUE

In [73]:
7 != 7

[1] FALSE

In [74]:
# Operator perbandingan pada vektor
v <- c(1,2,3,4,5)
v < 2

[1]  TRUE FALSE FALSE FALSE FALSE

In [75]:
v == 3

[1] FALSE FALSE  TRUE FALSE FALSE

In [76]:
v2 <- c(10,20,30,40,50)
v2

[1] 10 20 30 40 50

In [77]:
v < v2

[1] TRUE TRUE TRUE TRUE TRUE

## Pengindeksan dan pemotongan vektor

In [78]:
v1 <- c(10,20,30,40,50)
v2 <- c('a', 'b', 'c', 'd', 'e')

In [79]:
v1[2] # pengindeksan dimulai dari 1

[1] 20

In [80]:
v1[5]

[1] 50

In [81]:
v2[c(3,4,5)]

[1] "c" "d" "e"

In [82]:
v3 <- c(1,2,3,4,5,6,7,8,9,10)
v3[7:10]

[1]  7  8  9 10

In [83]:
v3[3:5]

[1] 3 4 5

In [84]:
b <- c(1,2,3,4,5,6)
names(b) <- c('I', 'G', 'D', 'O', 'R', 'E')
b

I G D O R E 
1 2 3 4 5 6

In [85]:
b[2]

G 
2

In [86]:
b['G']

G 
2

In [87]:
b[c(2,3)]

G D 
2 3

In [88]:
b[c('G', 'D')]

G D 
2 3

In [89]:
# Operator perbandingan
b

I G D O R E 
1 2 3 4 5 6

In [90]:
b[b>3]

O R E 
4 5 6

In [91]:
e <-  b > 3

In [92]:
b[e]

O R E 
4 5 6

# Matriks

## Mendefinisikan matriks

In [93]:
b <- 1:10
b

[1]  1  2  3  4  5  6  7  8  9 10

In [94]:
matrix(b) # 10 x 1

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

In [95]:
matrix(b, nrow=2, ncol= 5) # by column

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [96]:
matrix(b, nrow=2, ncol= 5, byrow = T) # by row

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10

In [97]:
matrix(1:12, nrow = 4, byrow=TRUE) # 4 x 3 by row

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [98]:
# Mendefinisikan matriks dari vektor
fb <- c(250,255,260,263,265) # bayangkan sebagai harga saham
ms <- c(455,460,465,479, 470)

In [99]:
saham <- c(fb, ms)
saham

[1] 250 255 260 263 265 455 460 465 479 470

In [100]:
matriks.saham <- matrix(saham, nrow=2, byrow=T)
matriks.saham

[,1] [,2] [,3] [,4] [,5]
[1,] 250  255  260  263  265 
[2,] 455  460  465  479  470

In [101]:
# Menamakan baris dan kolom

In [102]:
hari <- c('sen', 'sel', 'rab', 'kam', 'jum')
perusahaan <- c('fb', 'ms')

In [103]:
colnames(matriks.saham) <- hari
rownames(matriks.saham) <- perusahaan

In [104]:
matriks.saham

sen sel rab kam jum
fb 250 255 260 263 265
ms 455 460 465 479 470

## Aritmatika matriks

In [105]:
mat <- matrix(1:25, nrow=5, byrow=T)
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [106]:
mat * mat # element-by-element

[,1] [,2] [,3] [,4] [,5]
[1,]   1    4    9   16   25 
[2,]  36   49   64   81  100 
[3,] 121  144  169  196  225 
[4,] 256  289  324  361  400 
[5,] 441  484  529  576  625

In [107]:
mat / mat

[,1] [,2] [,3] [,4] [,5]
[1,] 1    1    1    1    1   
[2,] 1    1    1    1    1   
[3,] 1    1    1    1    1   
[4,] 1    1    1    1    1   
[5,] 1    1    1    1    1

In [108]:
mat^2

[,1] [,2] [,3] [,4] [,5]
[1,]   1    4    9   16   25 
[2,]  36   49   64   81  100 
[3,] 121  144  169  196  225 
[4,] 256  289  324  361  400 
[5,] 441  484  529  576  625

In [109]:
1 / mat

[,1]       [,2]       [,3]       [,4]       [,5]      
[1,] 1.00000000 0.50000000 0.33333333 0.25000000 0.20000000
[2,] 0.16666667 0.14285714 0.12500000 0.11111111 0.10000000
[3,] 0.09090909 0.08333333 0.07692308 0.07142857 0.06666667
[4,] 0.06250000 0.05882353 0.05555556 0.05263158 0.05000000
[5,] 0.04761905 0.04545455 0.04347826 0.04166667 0.04000000

In [110]:
# Operator perbandingan di matriks

In [111]:
mat > 10

[,1]  [,2]  [,3]  [,4]  [,5] 
[1,] FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE
[3,]  TRUE  TRUE  TRUE  TRUE  TRUE
[4,]  TRUE  TRUE  TRUE  TRUE  TRUE
[5,]  TRUE  TRUE  TRUE  TRUE  TRUE

In [112]:
mat[mat > 10]

[1] 11 16 21 12 17 22 13 18 23 14 19 24 15 20 25

In [113]:
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [114]:
# Perkalian matriks
mat %*% mat

[,1] [,2] [,3] [,4] [,5]
[1,]  215  230  245  260  275
[2,]  490  530  570  610  650
[3,]  765  830  895  960 1025
[4,] 1040 1130 1220 1310 1400
[5,] 1315 1430 1545 1660 1775

## Operasi - operasi di matriks

In [115]:
# Mendefinisikan matriks dari vektor
fb <- c(250,255,260,263,265)
ms <- c(455,460,465,479, 470)
saham <- c(fb, ms)
matriks.saham <- matrix(saham, nrow=2, byrow=T)
colnames(matriks.saham) <- c('sen', 'sel', 'rab', 'kam', 'jum')
rownames(matriks.saham) <-  c('fb', 'ms')
matriks.saham

sen sel rab kam jum
fb 250 255 260 263 265
ms 455 460 465 479 470

In [116]:
colSums(matriks.saham) # penjumlahan pada kolom

sen sel rab kam jum 
705 715 725 742 735

In [117]:
rowSums(matriks.saham)

fb   ms 
1293 2329

In [118]:
rowMeans(matriks.saham)

fb    ms 
258.6 465.8

In [119]:
colMeans(matriks.saham)

sen   sel   rab   kam   jum 
352.5 357.5 362.5 371.0 367.5

In [120]:
# Menambahkan kolom dan baris ke matriks

In [121]:
google <- c(175,180,185,195,190)
saham.int <- rbind(matriks.saham, google)
saham.int

sen sel rab kam jum
fb     250 255 260 263 265
ms     455 460 465 479 470
google 175 180 185 195 190

In [122]:
# Menambahkan kolom ke matriks
rata2 <- rowMeans(saham.int)
rata2

fb     ms google 
 258.6  465.8  185.0

In [123]:
saham.int <- cbind(saham.int, rata2)
saham.int

sen sel rab kam jum rata2
fb     250 255 260 263 265 258.6
ms     455 460 465 479 470 465.8
google 175 180 185 195 190 185.0

## Seleksi dan pengindeksan matriks

In [124]:
v <- c(10,20,30,40,50)
v

[1] 10 20 30 40 50

In [125]:
v[3]

[1] 30

In [126]:
mat <- matrix(1:25, nrow=5, byrow=T)
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [127]:
mat[1,] # baris 1, seluruh kolom

[1] 1 2 3 4 5

In [128]:
mat[2,3]

[1] 8

In [129]:
mat[3,4]

[1] 14

In [130]:
mat[,3]

[1]  3  8 13 18 23

In [131]:
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [132]:
mat[,5]

[1]  5 10 15 20 25

In [133]:
mat[1:3,] # baris 1 sampai 3

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15

In [134]:
mat[,4:5] # kolom 4 hingga 5

[,1] [,2]
[1,]  4    5  
[2,]  9   10  
[3,] 14   15  
[4,] 19   20  
[5,] 24   25

In [135]:
mat[1:2, 1:3] # baris 1 sampai 2, kolom 1 sampai 3

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 6    7    8

In [136]:
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [137]:
mat[3:5, 3:5]

[,1] [,2] [,3]
[1,] 13   14   15  
[2,] 18   19   20  
[3,] 23   24   25

## Fungsi `factor`

In [138]:
vek.warna <- c('merah', 'hijau', 'biru', 'merah', 'merah', 'hijau', 'biru')

In [139]:
vek.warna

[1] "merah" "hijau" "biru"  "merah" "merah" "hijau" "biru"

In [140]:
fact.warna <- factor(vek.warna, ordered=T, levels=c('merah', 'hijau', 'biru'))
fact.warna

[1] merah hijau biru  merah merah hijau biru 
Levels: merah < hijau < biru

In [141]:
summary(fact.warna)

merah hijau  biru 
    3     2     2

In [142]:
summary(vek.warna)

   Length     Class      Mode 
        7 character character 

# Data Frame

## Pengenalan

Kita banyak menggunakan data frame di dalam kegiatan analisis data, karena matriks hanya mampu menampung tipe data yang seragam.

In [143]:
state.x77 # built-in df

Population Income Illiteracy Life Exp Murder HS Grad Frost
Alabama         3615      3624   2.1        69.05    15.1   41.3     20  
Alaska           365      6315   1.5        69.31    11.3   66.7    152  
Arizona         2212      4530   1.8        70.55     7.8   58.1     15  
Arkansas        2110      3378   1.9        70.66    10.1   39.9     65  
California     21198      5114   1.1        71.71    10.3   62.6     20  
Colorado        2541      4884   0.7        72.06     6.8   63.9    166  
Connecticut     3100      5348   1.1        72.48     3.1   56.0    139  
Delaware         579      4809   0.9        70.06     6.2   54.6    103  
Florida         8277      4815   1.3        70.66    10.7   52.6     11  
Georgia         4931      4091   2.0        68.54    13.9   40.6     60  
Hawaii           868      4963   1.9        73.60     6.2   61.9      0  
Idaho            813      4119   0.6        71.87     5.3   59.5    126  
Illinois       11197      5107   0.9        70.14    10.3   52.6    127  
Indiana         5313      4458   0.7        70.88     7.1   52.9    122  
Iowa            2861      4628   0.5        72.56     2.3   59.0    140  
Kansas          2280      4669   0.6        72.58     4.5   59.9    114  
Kentucky        3387      3712   1.6        70.10    10.6   38.5     95  
Louisiana       3806      3545   2.8        68.76    13.2   42.2     12  
Maine           1058      3694   0.7        70.39     2.7   54.7    161  
Maryland        4122      5299   0.9        70.22     8.5   52.3    101  
Massachusetts   5814      4755   1.1        71.83     3.3   58.5    103  
Michigan        9111      4751   0.9        70.63    11.1   52.8    125  
Minnesota       3921      4675   0.6        72.96     2.3   57.6    160  
Mississippi     2341      3098   2.4        68.09    12.5   41.0     50  
Missouri        4767      4254   0.8        70.69     9.3   48.8    108  
Montana          746      4347   0.6        70.56     5.0   59.2    155  
Nebraska        1544      4508   0.6        72.60     2.9   59.3    139  
Nevada           590      5149   0.5        69.03    11.5   65.2    188  
New Hampshire    812      4281   0.7        71.23     3.3   57.6    174  
New Jersey      7333      5237   1.1        70.93     5.2   52.5    115  
New Mexico      1144      3601   2.2        70.32     9.7   55.2    120  
New York       18076      4903   1.4        70.55    10.9   52.7     82  
North Carolina  5441      3875   1.8        69.21    11.1   38.5     80  
North Dakota     637      5087   0.8        72.78     1.4   50.3    186  
Ohio           10735      4561   0.8        70.82     7.4   53.2    124  
Oklahoma        2715      3983   1.1        71.42     6.4   51.6     82  
Oregon          2284      4660   0.6        72.13     4.2   60.0     44  
Pennsylvania   11860      4449   1.0        70.43     6.1   50.2    126  
Rhode Island     931      4558   1.3        71.90     2.4   46.4    127  
South Carolina  2816      3635   2.3        67.96    11.6   37.8     65  
South Dakota     681      4167   0.5        72.08     1.7   53.3    172  
Tennessee       4173      3821   1.7        70.11    11.0   41.8     70  
Texas          12237      4188   2.2        70.90    12.2   47.4     35  
Utah            1203      4022   0.6        72.90     4.5   67.3    137  
Vermont          472      3907   0.6        71.64     5.5   57.1    168  
Virginia        4981      4701   1.4        70.08     9.5   47.8     85  
Washington      3559      4864   0.6        71.72     4.3   63.5     32  
West Virginia   1799      3617   1.4        69.48     6.7   41.6    100  
Wisconsin       4589      4468   0.7        72.48     3.0   54.5    149  
Wyoming          376      4566   0.6        70.29     6.9   62.9    173  
               Area  
Alabama         50708
Alaska         566432
Arizona        113417
Arkansas        51945
California     156361
Colorado       103766
Connecticut      4862
Delaware         1982
Florida         54090
Georgia         58073

In [144]:
USPersonalExpenditure

1940   1945   1950  1955 1960 
Food and Tobacco    22.200 44.500 59.60 73.2 86.80
Household Operation 10.500 15.500 29.00 36.5 46.20
Medical and Health   3.530  5.760  9.71 14.0 21.10
Personal Care        1.040  1.980  2.45  3.4  5.40
Private Education    0.341  0.974  1.80  2.6  3.64

In [145]:
# Mengetahui daftar built-in df
data()

In [146]:
head(state.x77) # 6 baris pertama

Population Income Illiteracy Life Exp Murder HS Grad Frost Area  
Alabama     3615      3624   2.1        69.05    15.1   41.3     20    50708
Alaska       365      6315   1.5        69.31    11.3   66.7    152   566432
Arizona     2212      4530   1.8        70.55     7.8   58.1     15   113417
Arkansas    2110      3378   1.9        70.66    10.1   39.9     65    51945
California 21198      5114   1.1        71.71    10.3   62.6     20   156361
Colorado    2541      4884   0.7        72.06     6.8   63.9    166   103766

In [147]:
tail(state.x77) # 6 baris terakhir

Population Income Illiteracy Life Exp Murder HS Grad Frost Area 
Vermont        472       3907   0.6        71.64    5.5    57.1    168    9267
Virginia      4981       4701   1.4        70.08    9.5    47.8     85   39780
Washington    3559       4864   0.6        71.72    4.3    63.5     32   66570
West Virginia 1799       3617   1.4        69.48    6.7    41.6    100   24070
Wisconsin     4589       4468   0.7        72.48    3.0    54.5    149   54464
Wyoming        376       4566   0.6        70.29    6.9    62.9    173   97203

In [148]:
str(state.x77) # struktur dari df

 num [1:50, 1:8] 3615 365 2212 2110 21198 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:50] "Alabama" "Alaska" "Arizona" "Arkansas" ...
  ..$ : chr [1:8] "Population" "Income" "Illiteracy" "Life Exp" ...


In [149]:
summary(state.x77) # sari statistik dari df berdasarkan kolom

   Population        Income       Illiteracy       Life Exp    
 Min.   :  365   Min.   :3098   Min.   :0.500   Min.   :67.96  
 1st Qu.: 1080   1st Qu.:3993   1st Qu.:0.625   1st Qu.:70.12  
 Median : 2838   Median :4519   Median :0.950   Median :70.67  
 Mean   : 4246   Mean   :4436   Mean   :1.170   Mean   :70.88  
 3rd Qu.: 4968   3rd Qu.:4814   3rd Qu.:1.575   3rd Qu.:71.89  
 Max.   :21198   Max.   :6315   Max.   :2.800   Max.   :73.60  
     Murder          HS Grad          Frost             Area       
 Min.   : 1.400   Min.   :37.80   Min.   :  0.00   Min.   :  1049  
 1st Qu.: 4.350   1st Qu.:48.05   1st Qu.: 66.25   1st Qu.: 36985  
 Median : 6.850   Median :53.25   Median :114.50   Median : 54277  
 Mean   : 7.378   Mean   :53.11   Mean   :104.46   Mean   : 70736  
 3rd Qu.:10.675   3rd Qu.:59.15   3rd Qu.:139.75   3rd Qu.: 81162  
 Max.   :15.100   Max.   :67.30   Max.   :188.00   Max.   :566432  

In [150]:
# mendefinisikan df
nama <- c('Agus', 'Sugio', 'Bayu', 'Atmo', 'Roy')
umur <- c(42,35,37,28,27)
kawin <- c(F,F,T,F,T)

In [151]:
data.frame(nama, umur, kawin)

nama  umur kawin
1 Agus  42   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE
4 Atmo  28   FALSE
5 Roy   27    TRUE

In [152]:
df <- data.frame(nama, umur, kawin)
df

nama  umur kawin
1 Agus  42   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE
4 Atmo  28   FALSE
5 Roy   27    TRUE

In [153]:
str(df)

'data.frame':	5 obs. of  3 variables:
 $ nama : Factor w/ 5 levels "Agus","Atmo",..: 1 5 3 2 4
 $ umur : num  42 35 37 28 27
 $ kawin: logi  FALSE FALSE TRUE FALSE TRUE


In [154]:
summary(df)

    nama        umur        kawin        
 Agus :1   Min.   :27.0   Mode :logical  
 Atmo :1   1st Qu.:28.0   FALSE:3        
 Bayu :1   Median :35.0   TRUE :2        
 Roy  :1   Mean   :33.8                  
 Sugio:1   3rd Qu.:37.0                  
           Max.   :42.0                  

## Seleksi dan pengindeksan Data Frame

In [155]:
df

nama  umur kawin
1 Agus  42   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE
4 Atmo  28   FALSE
5 Roy   27    TRUE

In [156]:
df[3, ] # ambil baris ketiga

nama umur kawin
3 Bayu 37   TRUE

In [157]:
df[,1]

[1] Agus  Sugio Bayu  Atmo  Roy  
Levels: Agus Atmo Bayu Roy Sugio

In [158]:
df[,'nama']

[1] Agus  Sugio Bayu  Atmo  Roy  
Levels: Agus Atmo Bayu Roy Sugio

In [159]:
df[1:4, c('nama', 'umur')]

nama  umur
1 Agus  42  
2 Sugio 35  
3 Bayu  37  
4 Atmo  28

In [160]:
df$umur

[1] 42 35 37 28 27

In [161]:
df[,'umur']

[1] 42 35 37 28 27

In [162]:
# fungsi subset
df

nama  umur kawin
1 Agus  42   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE
4 Atmo  28   FALSE
5 Roy   27    TRUE

In [163]:
subset(df,subset = kawin == T) 

nama umur kawin
3 Bayu 37   TRUE 
5 Roy  27   TRUE

In [164]:
subset(df, subset = umur > 30)

nama  umur kawin
1 Agus  42   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE

In [165]:
# Mengurutkan dataframe
urut.umur <- order(df['umur'])
urut.umur

[1] 5 4 2 3 1

In [166]:
df[urut.umur,]

nama  umur kawin
5 Roy   27    TRUE
4 Atmo  28   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE
1 Agus  42   FALSE

In [167]:
umur.terbalik <- order(-df['umur'])
umur.terbalik

[1] 1 3 2 4 5

In [168]:
df[umur.terbalik,]

nama  umur kawin
1 Agus  42   FALSE
3 Bayu  37    TRUE
2 Sugio 35   FALSE
4 Atmo  28   FALSE
5 Roy   27    TRUE

In [169]:
urut.umur <- order(df$umur)
df[urut.umur, ]

nama  umur kawin
5 Roy   27    TRUE
4 Atmo  28   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE
1 Agus  42   FALSE

## Operasi - operasi data frame

### Mendefinisikan data frame

In [170]:
c1 <- 1:10
c2 <- letters[1:10]
print(c1)
print(c2)

 [1]  1  2  3  4  5  6  7  8  9 10
 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j"


In [171]:
df <- data.frame(c1,c2)
df

c1 c2
1   1 a 
2   2 b 
3   3 c 
4   4 d 
5   5 e 
6   6 f 
7   7 g 
8   8 h 
9   9 i 
10 10 j

In [172]:
df <- data.frame(kolom1 = c1, kolom2 = c2) # nama kolom bisa kita ubah sesuka kita!
df

kolom1 kolom2
1   1     a     
2   2     b     
3   3     c     
4   4     d     
5   5     e     
6   6     f     
7   7     g     
8   8     h     
9   9     i     
10 10     j

### Mendapatkan info tentang data frame

In [173]:
nrow(df) # jumlah baris

[1] 10

In [174]:
ncol(df) # jumlah kolom

[1] 2

In [175]:
colnames(df)  # nama kolom

[1] "kolom1" "kolom2"

In [176]:
rownames(df) # nama baris

[1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [177]:
str(df) # struktur data frame

'data.frame':	10 obs. of  2 variables:
 $ kolom1: int  1 2 3 4 5 6 7 8 9 10
 $ kolom2: Factor w/ 10 levels "a","b","c","d",..: 1 2 3 4 5 6 7 8 9 10


In [178]:
summary(df) # sari statistik

     kolom1          kolom2 
 Min.   : 1.00   a      :1  
 1st Qu.: 3.25   b      :1  
 Median : 5.50   c      :1  
 Mean   : 5.50   d      :1  
 3rd Qu.: 7.75   e      :1  
 Max.   :10.00   f      :1  
                 (Other):4  

### Referensi sel

In [179]:
df

kolom1 kolom2
1   1     a     
2   2     b     
3   3     c     
4   4     d     
5   5     e     
6   6     f     
7   7     g     
8   8     h     
9   9     i     
10 10     j

In [180]:
df[5,1]

[1] 5

In [181]:
df[[5,1]]

[1] 5

In [182]:
df[1,'kolom1']

[1] 1

In [183]:
df[5, 'kolom1']

[1] 5

In [184]:
df[[5,'kolom1']]

[1] 5

In [185]:
df[8,'kolom1'] <- -999 # mengubah nilai
df

kolom1 kolom2
1     1   a     
2     2   b     
3     3   c     
4     4   d     
5     5   e     
6     6   f     
7     7   g     
8  -999   h     
9     9   i     
10   10   j

In [186]:
df[[8,'kolom1']] <- 8
df

kolom1 kolom2
1   1     a     
2   2     b     
3   3     c     
4   4     d     
5   5     e     
6   6     f     
7   7     g     
8   8     h     
9   9     i     
10 10     j

### Referensi baris dan kolom

In [187]:
df[2,]

kolom1 kolom2
2 2      b

In [188]:
df[1:3,]

kolom1 kolom2
1 1      a     
2 2      b     
3 3      c

In [189]:
head(mtcars)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [190]:
mtcars$mpg

[1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

In [191]:
mtcars[,1]

[1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

In [192]:
mtcars[,'mpg']

[1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

In [193]:
mtcars[['mpg']]

[1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

In [194]:
mtcars[1] # indeks lokasi kolom:1, cara ini mereferensi kolom mpg sbg data frame

mpg 
Mazda RX4           21.0
Mazda RX4 Wag       21.0
Datsun 710          22.8
Hornet 4 Drive      21.4
Hornet Sportabout   18.7
Valiant             18.1
Duster 360          14.3
Merc 240D           24.4
Merc 230            22.8
Merc 280            19.2
Merc 280C           17.8
Merc 450SE          16.4
Merc 450SL          17.3
Merc 450SLC         15.2
Cadillac Fleetwood  10.4
Lincoln Continental 10.4
Chrysler Imperial   14.7
Fiat 128            32.4
Honda Civic         30.4
Toyota Corolla      33.9
Toyota Corona       21.5
Dodge Challenger    15.5
AMC Javelin         15.2
Camaro Z28          13.3
Pontiac Firebird    19.2
Fiat X1-9           27.3
Porsche 914-2       26.0
Lotus Europa        30.4
Ford Pantera L      15.8
Ferrari Dino        19.7
Maserati Bora       15.0
Volvo 142E          21.4

In [195]:
head(mtcars)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [196]:
mtcars[c('mpg', 'cyl')]

mpg  cyl
Mazda RX4           21.0 6  
Mazda RX4 Wag       21.0 6  
Datsun 710          22.8 4  
Hornet 4 Drive      21.4 6  
Hornet Sportabout   18.7 8  
Valiant             18.1 6  
Duster 360          14.3 8  
Merc 240D           24.4 4  
Merc 230            22.8 4  
Merc 280            19.2 6  
Merc 280C           17.8 6  
Merc 450SE          16.4 8  
Merc 450SL          17.3 8  
Merc 450SLC         15.2 8  
Cadillac Fleetwood  10.4 8  
Lincoln Continental 10.4 8  
Chrysler Imperial   14.7 8  
Fiat 128            32.4 4  
Honda Civic         30.4 4  
Toyota Corolla      33.9 4  
Toyota Corona       21.5 4  
Dodge Challenger    15.5 8  
AMC Javelin         15.2 8  
Camaro Z28          13.3 8  
Pontiac Firebird    19.2 8  
Fiat X1-9           27.3 4  
Porsche 914-2       26.0 4  
Lotus Europa        30.4 4  
Ford Pantera L      15.8 8  
Ferrari Dino        19.7 6  
Maserati Bora       15.0 8  
Volvo 142E          21.4 4

### Menambahkan baris dan kolom

In [197]:
c1 <- c(10,20,30,40,50)
c2 <- letters[c(1:5)]
df <- data.frame(kol1=c1,kol2=c2)
df

kol1 kol2
1 10   a   
2 20   b   
3 30   c   
4 40   d   
5 50   e

In [198]:
df1 <- data.frame(kol1=128,kol2='Meteorologi')
df1

kol1 kol2       
1 128  Meteorologi

In [199]:
# menambahkan df1 ke df
df <- rbind(df,df1)
df

kol1 kol2       
1  10  a          
2  20  b          
3  30  c          
4  40  d          
5  50  e          
6 128  Meteorologi

In [200]:
c3 <- c(11:16)
c3

[1] 11 12 13 14 15 16

In [201]:
# menambahkan kolom ke df
df <- cbind(df,kol3=c3)
df

kol1 kol2        kol3
1  10  a           11  
2  20  b           12  
3  30  c           13  
4  40  d           14  
5  50  e           15  
6 128  Meteorologi 16

In [202]:
df$kol4 <- c(20,25,30,35,40,45)
df

kol1 kol2        kol3 kol4
1  10  a           11   20  
2  20  b           12   25  
3  30  c           13   30  
4  40  d           14   35  
5  50  e           15   40  
6 128  Meteorologi 16   45

In [203]:
df$kol5 <- df$kol1 * 2
df

kol1 kol2        kol3 kol4 kol5
1  10  a           11   20    20 
2  20  b           12   25    40 
3  30  c           13   30    60 
4  40  d           14   35    80 
5  50  e           15   40   100 
6 128  Meteorologi 16   45   256

### Mengatur penamaan kolom

In [204]:
colnames(df) # mengetahui nama kolom

[1] "kol1" "kol2" "kol3" "kol4" "kol5"

In [205]:
colnames(df) <- c('A', 'B', 'C', 'D', 'E') # penamaan ulang nama kolom
df

A   B           C  D  E  
1  10 a           11 20  20
2  20 b           12 25  40
3  30 c           13 30  60
4  40 d           14 35  80
5  50 e           15 40 100
6 128 Meteorologi 16 45 256

In [206]:
colnames(df)[1] <- 'X' # penamaan ulang kolom secara individual
df

X   B           C  D  E  
1  10 a           11 20  20
2  20 b           12 25  40
3  30 c           13 30  60
4  40 d           14 35  80
5  50 e           15 40 100
6 128 Meteorologi 16 45 256

In [207]:
colnames(df)[c(2,3)] <- c('Y','Z')
df

X   Y           Z  D  E  
1  10 a           11 20  20
2  20 b           12 25  40
3  30 c           13 30  60
4  40 d           14 35  80
5  50 e           15 40 100
6 128 Meteorologi 16 45 256

### Menyeleksi banyak baris dan kolom

In [208]:
df[1:3,]

X  Y Z  D  E 
1 10 a 11 20 20
2 20 b 12 25 40
3 30 c 13 30 60

In [209]:
# menyeleksi seluruh baris, kecuali no 3
df[-3,]

X   Y           Z  D  E  
1  10 a           11 20  20
2  20 b           12 25  40
4  40 d           14 35  80
5  50 e           15 40 100
6 128 Meteorologi 16 45 256

In [210]:
# penyeleksian kondisional
head(mtcars)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [211]:
mtcars[mtcars$mpg > 20,]

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4      21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag  21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Datsun 710     22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive 21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Merc 240D      24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2   
Merc 230       22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Fiat 128       32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1   
Honda Civic    30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2   
Toyota Corolla 33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1   
Toyota Corona  21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1   
Fiat X1-9      27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1   
Porsche 914-2  26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2   
Lotus Europa   30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2   
Volvo 142E     21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [212]:
mtcars[mtcars$mpg > 20 & mtcars$cyl == 6,]

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4      21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag  21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Hornet 4 Drive 21.4 6   258  110 3.08 3.215 19.44 1  0  3    1

In [213]:
mtcars[mtcars$mpg > 20 & mtcars$cyl == 6, c('mpg', 'cyl','hp')]

mpg  cyl hp 
Mazda RX4      21.0 6   110
Mazda RX4 Wag  21.0 6   110
Hornet 4 Drive 21.4 6   110

In [214]:
subset(mtcars, mpg > 20 & cyl == 6) # pakai built-in subset function

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4      21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag  21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Hornet 4 Drive 21.4 6   258  110 3.08 3.215 19.44 1  0  3    1

In [215]:
df[,1:3]

X   Y           Z 
1  10 a           11
2  20 b           12
3  30 c           13
4  40 d           14
5  50 e           15
6 128 Meteorologi 16

In [216]:
df[,c(3,5)]

Z  E  
1 11  20
2 12  40
3 13  60
4 14  80
5 15 100
6 16 256

In [217]:
df[,c('Z', 'E')]

Z  E  
1 11  20
2 12  40
3 13  60
4 14  80
5 15 100
6 16 256

### Menangani data kosong

In [218]:
df

X   Y           Z  D  E  
1  10 a           11 20  20
2  20 b           12 25  40
3  30 c           13 30  60
4  40 d           14 35  80
5  50 e           15 40 100
6 128 Meteorologi 16 45 256

In [219]:
is.na(df) # cek data kosong

X     Y     Z     D     E    
[1,] FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE
[3,] FALSE FALSE FALSE FALSE FALSE
[4,] FALSE FALSE FALSE FALSE FALSE
[5,] FALSE FALSE FALSE FALSE FALSE
[6,] FALSE FALSE FALSE FALSE FALSE

In [220]:
any(is.na(df))

[1] FALSE

In [221]:
any(is.na(df$X))

[1] FALSE

In [222]:
# Membuat na jadi 0
any(is.na(df)) <- 0.5 # error karena ga ada na

ERROR: Error in any(is.na(df)) <- 0.5: could not find function "any<-"


In [224]:
any(is.na(df$D)) <- mean(df$D)  # error karena ga ada na

ERROR: Error in any(is.na(df$D)) <- mean(df$D): could not find function "any<-"


# List

Kumpulan berbagai macam tipe data di R

In [225]:
v <- c(1,2,3,4,5)
M <- matrix(1:10, nrow=2)
c1 <- c('Ignatius', 'Laynez', 'Faber', 'Xaverius', 'Kanisius')
c2 <- c(42,37,28,45,43)

In [226]:
df <- data.frame(Nama = c1, ID = c2)
df

Nama     ID
1 Ignatius 42
2 Laynez   37
3 Faber    28
4 Xaverius 45
5 Kanisius 43

In [227]:
# Pendefinisian list
l <- list(v,M,df)
l

[[1]]
[1] 1 2 3 4 5

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[[3]]
      Nama ID
1 Ignatius 42
2   Laynez 37
3    Faber 28
4 Xaverius 45
5 Kanisius 43

In [228]:
# penamaaan ulang indeks list

l2 <- list(sampel_vektor = v, sampel_matriks = M, sample_data_frame = df)
l2

$sampel_vektor
[1] 1 2 3 4 5

$sampel_matriks
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_data_frame
      Nama ID
1 Ignatius 42
2   Laynez 37
3    Faber 28
4 Xaverius 45
5 Kanisius 43

In [230]:
l2[1]

$sampel_vektor
[1] 1 2 3 4 5

In [231]:
l2['sampel_vektor']

$sampel_vektor
[1] 1 2 3 4 5

In [232]:
l2$sampel_vektor

[1] 1 2 3 4 5

In [233]:
l2[['sampel_vektor']]

[1] 1 2 3 4 5

In [236]:
print(class(l2['sampel_vektor']))
print(class(l2[1]))

[1] "list"
[1] "list"


In [239]:
print(class(l2$sampel_vektor))
print(class(l2[['sampel_vektor']]))

[1] "numeric"
[1] "numeric"


In [241]:
# Mengombinasikan dua list
l3 <- c(l,l2)
l3

[[1]]
[1] 1 2 3 4 5

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[[3]]
      Nama ID
1 Ignatius 42
2   Laynez 37
3    Faber 28
4 Xaverius 45
5 Kanisius 43

$sampel_vektor
[1] 1 2 3 4 5

$sampel_matriks
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_data_frame
      Nama ID
1 Ignatius 42
2   Laynez 37
3    Faber 28
4 Xaverius 45
5 Kanisius 43

In [242]:
str(l2)

List of 3
 $ sampel_vektor    : num [1:5] 1 2 3 4 5
 $ sampel_matriks   : int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
 $ sample_data_frame:'data.frame':	5 obs. of  2 variables:
  ..$ Nama: Factor w/ 5 levels "Faber","Ignatius",..: 2 4 1 5 3
  ..$ ID  : num [1:5] 42 37 28 45 43


In [243]:
summary(l2)

                  Length Class      Mode   
sampel_vektor      5     -none-     numeric
sampel_matriks    10     -none-     numeric
sample_data_frame  2     data.frame list   

# Penanganan data tabular

## Penanganan data csv

In [245]:
getwd() # tahu di mana posisi kita saat ini

[1] "/home/ronggolawe/coding_repo/statdasWebinaR"

In [246]:
setwd("/home//ronggolawe/coding_repo/statdasWebinaR/") # mengatur posisi kita

In [247]:
getwd()

[1] "/home/ronggolawe/coding_repo/statdasWebinaR"

In [2]:
# Membaca csv
data <- read.csv("gaji.csv")
data

ID NAMA       Gaji     Jurusan           
1 1  Petrus      1000000 Teologi           
2 2  Matius      2000000 Filsafat          
3 3  Markus      5000000 Meteorologi       
4 4  Barnabas   10000000 Teknik Informatika
5 5  Thomas     20000000 Sistem Informasi  
6 6  Ignatius     500000 Pendidikan Agama  
7 7  Aisyah     25000000 Teknik Elektro    
8 8  Supriyanto  1500000 Ilmu Perpustakaan

In [3]:
# menuliskan csv
head(mtcars)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [4]:
write.csv(mtcars, file = "tes.csv")

In [6]:
class(data)

[1] "data.frame"

In [10]:
# menuliskan csv dari data frame
c1 <- c(10,20,30,40,50)
c2 <- c('A', 'B', 'C', 'D', 'E')
df <- data.frame(c1,c2)
df

c1 c2
1 10 A 
2 20 B 
3 30 C 
4 40 D 
5 50 E

In [11]:
write.csv(df, file = 'tes2.csv')

In [12]:
help(read.csv)

## Penanganan data excel

In [ ]:
insta