&copy; 2020<br><br>
Oleh:<br><br>
Sandy Hardian Susanto Herho<br>
[herholabs@protonmail.ch](mailto:herholabs@protonmail.ch)<br><br>
Dasapta Erwin Irawan<br>
[r-win@office.itb.ac.id](mailto:r-win@office.itb.ac.id)

# Dasar - dasar pemrograman

## Aritmatika

In [1]:
1 + 2

[1] 3

In [2]:
5 - 3

[1] 2

In [3]:
5.25 + 3.95

[1] 9.2

In [4]:
3 * 2

[1] 6

In [5]:
15 / 2

[1] 7.5

In [6]:
2 ^ 3

[1] 8

In [7]:
# operator modulus

15/2 

[1] 7.5

In [8]:
15 %% 2

[1] 1

In [9]:
# urutan operasi
15 * 20 + 50 / 2

[1] 325

In [10]:
15 * 20 + (50 / 2)

[1] 325

In [11]:
15 * (20 + 50) / 2

[1] 525

## Variabel

In [12]:
# komentar
v <- 10

In [13]:
print(v)

[1] 10


In [14]:
v

[1] 10

In [15]:
uang <- 100000

In [16]:
uang

[1] 1e+05

In [17]:
tiket.bioskop <- 2e5 # paling sering digunakan di komunitas R
tiket.bioskop

[1] 2e+05

In [18]:
tiketBioskop <- 2.05e5
tiketBioskop

[1] 205000

In [19]:
tiket_bioskop <-2.1e5
tiket_bioskop

[1] 210000

In [20]:
popcorn <- 5e4
popcorn

[1] 50000

In [21]:
tiket.bioskop <- tiket.bioskop + popcorn + 2e4
print(tiket.bioskop)

[1] 270000


## Tipe - tipe data

### Numerik

In [22]:
b <- 2
b

[1] 2

In [23]:
d <- 3.5
d

[1] 3.5

In [24]:
class(d)

[1] "numeric"

In [25]:
class(b)

[1] "numeric"

Integer dan float di R dianggap sebagai tipe data numerik

### Logical

In [26]:
TRUE

[1] TRUE

In [27]:
FALSE

[1] FALSE

In [28]:
T

[1] TRUE

In [29]:
F

[1] FALSE

In [30]:
a <- TRUE
a

[1] TRUE

In [31]:
class(a)

[1] "logical"

### Character

In [32]:
"Halo"

[1] "Halo"

In [33]:
'Halo'

[1] "Halo"

In [34]:
txt <- "Hello world!"
print(txt)

[1] "Hello world!"


In [35]:
class(txt)

[1] "character"

## Vektor

In [36]:
num <- c(1,2,3,4,5)

In [37]:
class(num)

[1] "numeric"

In [38]:
txt <- c('a', 'b', 'c')
txt

[1] "a" "b" "c"

In [39]:
class(txt)

[1] "character"

In [40]:
l <- c(T,F)
l

[1]  TRUE FALSE

In [41]:
class(l)

[1] "logical"

In [42]:
v1 <- c(TRUE, 10, 20)
v1

[1]  1 10 20

In [43]:
class(v1) # logical dikonversi menjadi numeric

[1] "numeric"

In [44]:
v2 <- c('a', 'b', 20)
v2

[1] "a"  "b"  "20"

In [45]:
class(v2) # numeric dikonversi menjadi character

[1] "character"

In [46]:
v3 <- c(TRUE, 128, 'Meteorologi')
v3

[1] "TRUE"        "128"         "Meteorologi"

In [47]:
class(v3) # logical & numeric dikonversi menjadi character

[1] "character"

In [48]:
# names : metode penamaaan vektor (metode 1) 
hari <- c(1,2,3,4,5,6,7)
hari

[1] 1 2 3 4 5 6 7

In [49]:
names(hari) <- c('sen', 'sel', 'rab', 'kam', 'jum', 'sab', 'min')

In [50]:
hari

sen sel rab kam jum sab min 
  1   2   3   4   5   6   7

In [51]:
# names : metode penamaaan vektor (metode 2)
b <-  c('sen', 'sel', 'rab', 'kam', 'jum', 'sab', 'min')
names(hari) <- b
hari

sen sel rab kam jum sab min 
  1   2   3   4   5   6   7

In [52]:
hari['sen']

sen 
  1

In [53]:
hari[1]

sen 
  1

## Operasi - operasi vektor

In [54]:
v1 <- c(1,2,3,4,5)
v2 <- c(6,7,8,9,10)

In [55]:
v1 + v2 # element-by-element

[1]  7  9 11 13 15

In [56]:
v1 - v2

[1] -5 -5 -5 -5 -5

In [57]:
v1 * v2

[1]  6 14 24 36 50

In [58]:
v2 / v2

[1] 1 1 1 1 1

In [59]:
sum(v1) # jumlah seluruh v1

[1] 15

In [60]:
mean(v1) # rata2 v1

[1] 3

In [61]:
sd(v1) # std v1

[1] 1.581139

In [62]:
max(v2)

[1] 10

In [63]:
min(v2)

[1] 6

In [64]:
prod(v1) # mengalikan seluruh elemen di vektor 

[1] 120

In [65]:
prod(v2)

[1] 30240

In [66]:
b <- sum(v1)
print(b)

[1] 15


## Operator - operator perbandingan

In [67]:
4 > 5

[1] FALSE

In [68]:
7 > 4

[1] TRUE

In [69]:
10 >= 5

[1] TRUE

In [70]:
7 <= 5

[1] FALSE

In [71]:
8 == 8

[1] TRUE

In [72]:
7 != 15

[1] TRUE

In [73]:
7 != 7

[1] FALSE

In [74]:
# Operator perbandingan pada vektor
v <- c(1,2,3,4,5)
v < 2

[1]  TRUE FALSE FALSE FALSE FALSE

In [75]:
v == 3

[1] FALSE FALSE  TRUE FALSE FALSE

In [76]:
v2 <- c(10,20,30,40,50)
v2

[1] 10 20 30 40 50

In [77]:
v < v2

[1] TRUE TRUE TRUE TRUE TRUE

## Pengindeksan dan pemotongan vektor

In [79]:
v1 <- c(10,20,30,40,50)
v2 <- c('a', 'b', 'c', 'd', 'e')

In [80]:
v1[2] # pengindeksan dimulai dari 1

[1] 20

In [84]:
v1[5]

[1] 50

In [86]:
v2[c(3,4,5)]

[1] "c" "d" "e"

In [1]:
v3 <- c(1,2,3,4,5,6,7,8,9,10)
v3[7:10]

[1]  7  8  9 10

In [2]:
v3[3:5]

[1] 3 4 5

In [5]:
b <- c(1,2,3,4,5,6)
names(b) <- c('I', 'G', 'D', 'O', 'R', 'E')
b

I G D O R E 
1 2 3 4 5 6

In [6]:
b[2]

G 
2

In [7]:
b['G']

G 
2

In [8]:
b[c(2,3)]

G D 
2 3

In [9]:
b[c('G', 'D')]

G D 
2 3

In [10]:
# Operator perbandingan
b

I G D O R E 
1 2 3 4 5 6

In [11]:
b[b>3]

O R E 
4 5 6

In [12]:
e <-  b > 3

In [13]:
b[e]

O R E 
4 5 6

# Matriks

## Mendefinisikan matriks

In [15]:
b <- 1:10
b

[1]  1  2  3  4  5  6  7  8  9 10

In [16]:
matrix(b) # 10 x 1

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

In [19]:
matrix(b, nrow=2, ncol= 5) # by column

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [20]:
matrix(b, nrow=2, ncol= 5, byrow = T) # by row

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10

In [22]:
matrix(1:12, nrow = 4, byrow=TRUE) # 4 x 3 by row

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [24]:
# Mendefinisikan matriks dari vektor
fb <- c(250,255,260,263,265) # bayangkan sebagai harga saham
ms <- c(455,460,465,479, 470)

In [26]:
saham <- c(fb, ms)
saham

[1] 250 255 260 263 265 455 460 465 479 470

In [29]:
matriks.saham <- matrix(saham, nrow=2, byrow=T)
matriks.saham

[,1] [,2] [,3] [,4] [,5]
[1,] 250  255  260  263  265 
[2,] 455  460  465  479  470

In [30]:
# Menamakan baris dan kolom

In [32]:
hari <- c('sen', 'sel', 'rab', 'kam', 'jum')
perusahaan <- c('fb', 'ms')

In [33]:
colnames(matriks.saham) <- hari
rownames(matriks.saham) <- perusahaan

In [34]:
matriks.saham

sen sel rab kam jum
fb 250 255 260 263 265
ms 455 460 465 479 470

## Aritmatika matriks

In [36]:
mat <- matrix(1:25, nrow=5, byrow=T)
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [37]:
mat * mat # element-by-element

[,1] [,2] [,3] [,4] [,5]
[1,]   1    4    9   16   25 
[2,]  36   49   64   81  100 
[3,] 121  144  169  196  225 
[4,] 256  289  324  361  400 
[5,] 441  484  529  576  625

In [38]:
mat / mat

[,1] [,2] [,3] [,4] [,5]
[1,] 1    1    1    1    1   
[2,] 1    1    1    1    1   
[3,] 1    1    1    1    1   
[4,] 1    1    1    1    1   
[5,] 1    1    1    1    1

In [39]:
mat^2

[,1] [,2] [,3] [,4] [,5]
[1,]   1    4    9   16   25 
[2,]  36   49   64   81  100 
[3,] 121  144  169  196  225 
[4,] 256  289  324  361  400 
[5,] 441  484  529  576  625

In [40]:
1 / mat

[,1]       [,2]       [,3]       [,4]       [,5]      
[1,] 1.00000000 0.50000000 0.33333333 0.25000000 0.20000000
[2,] 0.16666667 0.14285714 0.12500000 0.11111111 0.10000000
[3,] 0.09090909 0.08333333 0.07692308 0.07142857 0.06666667
[4,] 0.06250000 0.05882353 0.05555556 0.05263158 0.05000000
[5,] 0.04761905 0.04545455 0.04347826 0.04166667 0.04000000

In [41]:
# Operator perbandingan di matriks

In [42]:
mat > 10

[,1]  [,2]  [,3]  [,4]  [,5] 
[1,] FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE
[3,]  TRUE  TRUE  TRUE  TRUE  TRUE
[4,]  TRUE  TRUE  TRUE  TRUE  TRUE
[5,]  TRUE  TRUE  TRUE  TRUE  TRUE

In [43]:
mat[mat > 10]

[1] 11 16 21 12 17 22 13 18 23 14 19 24 15 20 25

In [44]:
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [45]:
# Perkalian matriks
mat %*% mat

[,1] [,2] [,3] [,4] [,5]
[1,]  215  230  245  260  275
[2,]  490  530  570  610  650
[3,]  765  830  895  960 1025
[4,] 1040 1130 1220 1310 1400
[5,] 1315 1430 1545 1660 1775

## Operasi - operasi di matriks

In [54]:
# Mendefinisikan matriks dari vektor
fb <- c(250,255,260,263,265)
ms <- c(455,460,465,479, 470)
saham <- c(fb, ms)
matriks.saham <- matrix(saham, nrow=2, byrow=T)
colnames(matriks.saham) <- c('sen', 'sel', 'rab', 'kam', 'jum')
rownames(matriks.saham) <-  c('fb', 'ms')
matriks.saham

sen sel rab kam jum
fb 250 255 260 263 265
ms 455 460 465 479 470

In [55]:
colSums(matriks.saham) # penjumlahan pada kolom

sen sel rab kam jum 
705 715 725 742 735

In [56]:
rowSums(matriks.saham)

fb   ms 
1293 2329

In [57]:
rowMeans(matriks.saham)

fb    ms 
258.6 465.8

In [58]:
colMeans(matriks.saham)

sen   sel   rab   kam   jum 
352.5 357.5 362.5 371.0 367.5

In [59]:
# Menambahkan kolom dan baris ke matriks

In [64]:
google <- c(175,180,185,195,190)
saham.int <- rbind(matriks.saham, google)
saham.int

sen sel rab kam jum
fb     250 255 260 263 265
ms     455 460 465 479 470
google 175 180 185 195 190

In [66]:
# Menambahkan kolom ke matriks
rata2 <- rowMeans(saham.int)
rata2

fb     ms google 
 258.6  465.8  185.0

In [67]:
saham.int <- cbind(saham.int, rata2)
saham.int

sen sel rab kam jum rata2
fb     250 255 260 263 265 258.6
ms     455 460 465 479 470 465.8
google 175 180 185 195 190 185.0

## Seleksi dan pengindeksan matriks

In [68]:
v <- c(10,20,30,40,50)
v

[1] 10 20 30 40 50

In [69]:
v[3]

[1] 30

In [2]:
mat <- matrix(1:25, nrow=5, byrow=T)
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [3]:
mat[1,] # baris 1, seluruh kolom

[1] 1 2 3 4 5

In [4]:
mat[2,3]

[1] 8

In [5]:
mat[3,4]

[1] 14

In [6]:
mat[,3]

[1]  3  8 13 18 23

In [7]:
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [8]:
mat[,5]

[1]  5 10 15 20 25

In [11]:
mat[1:3,] # baris 1 sampai 3

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15

In [12]:
mat[,4:5] # kolom 4 hingga 5

[,1] [,2]
[1,]  4    5  
[2,]  9   10  
[3,] 14   15  
[4,] 19   20  
[5,] 24   25

In [14]:
mat[1:2, 1:3] # baris 1 sampai 2, kolom 1 sampai 3

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 6    7    8

In [15]:
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [16]:
mat[3:5, 3:5]

[,1] [,2] [,3]
[1,] 13   14   15  
[2,] 18   19   20  
[3,] 23   24   25

## Fungsi `factor`

In [18]:
vek.warna <- c('merah', 'hijau', 'biru', 'merah', 'merah', 'hijau', 'biru')

In [19]:
vek.warna

[1] "merah" "hijau" "biru"  "merah" "merah" "hijau" "biru"

In [23]:
fact.warna <- factor(vek.warna, ordered=T, levels=c('merah', 'hijau', 'biru'))
fact.warna

[1] merah hijau biru  merah merah hijau biru 
Levels: merah < hijau < biru

In [24]:
summary(fact.warna)

merah hijau  biru 
    3     2     2

In [25]:
summary(vek.warna)

   Length     Class      Mode 
        7 character character 

# Data Frame

## Pengenalan

In [27]:
state.x77 # built-in df

Population Income Illiteracy Life Exp Murder HS Grad Frost
Alabama         3615      3624   2.1        69.05    15.1   41.3     20  
Alaska           365      6315   1.5        69.31    11.3   66.7    152  
Arizona         2212      4530   1.8        70.55     7.8   58.1     15  
Arkansas        2110      3378   1.9        70.66    10.1   39.9     65  
California     21198      5114   1.1        71.71    10.3   62.6     20  
Colorado        2541      4884   0.7        72.06     6.8   63.9    166  
Connecticut     3100      5348   1.1        72.48     3.1   56.0    139  
Delaware         579      4809   0.9        70.06     6.2   54.6    103  
Florida         8277      4815   1.3        70.66    10.7   52.6     11  
Georgia         4931      4091   2.0        68.54    13.9   40.6     60  
Hawaii           868      4963   1.9        73.60     6.2   61.9      0  
Idaho            813      4119   0.6        71.87     5.3   59.5    126  
Illinois       11197      5107   0.9        70.14    10.3   52.6    127  
Indiana         5313      4458   0.7        70.88     7.1   52.9    122  
Iowa            2861      4628   0.5        72.56     2.3   59.0    140  
Kansas          2280      4669   0.6        72.58     4.5   59.9    114  
Kentucky        3387      3712   1.6        70.10    10.6   38.5     95  
Louisiana       3806      3545   2.8        68.76    13.2   42.2     12  
Maine           1058      3694   0.7        70.39     2.7   54.7    161  
Maryland        4122      5299   0.9        70.22     8.5   52.3    101  
Massachusetts   5814      4755   1.1        71.83     3.3   58.5    103  
Michigan        9111      4751   0.9        70.63    11.1   52.8    125  
Minnesota       3921      4675   0.6        72.96     2.3   57.6    160  
Mississippi     2341      3098   2.4        68.09    12.5   41.0     50  
Missouri        4767      4254   0.8        70.69     9.3   48.8    108  
Montana          746      4347   0.6        70.56     5.0   59.2    155  
Nebraska        1544      4508   0.6        72.60     2.9   59.3    139  
Nevada           590      5149   0.5        69.03    11.5   65.2    188  
New Hampshire    812      4281   0.7        71.23     3.3   57.6    174  
New Jersey      7333      5237   1.1        70.93     5.2   52.5    115  
New Mexico      1144      3601   2.2        70.32     9.7   55.2    120  
New York       18076      4903   1.4        70.55    10.9   52.7     82  
North Carolina  5441      3875   1.8        69.21    11.1   38.5     80  
North Dakota     637      5087   0.8        72.78     1.4   50.3    186  
Ohio           10735      4561   0.8        70.82     7.4   53.2    124  
Oklahoma        2715      3983   1.1        71.42     6.4   51.6     82  
Oregon          2284      4660   0.6        72.13     4.2   60.0     44  
Pennsylvania   11860      4449   1.0        70.43     6.1   50.2    126  
Rhode Island     931      4558   1.3        71.90     2.4   46.4    127  
South Carolina  2816      3635   2.3        67.96    11.6   37.8     65  
South Dakota     681      4167   0.5        72.08     1.7   53.3    172  
Tennessee       4173      3821   1.7        70.11    11.0   41.8     70  
Texas          12237      4188   2.2        70.90    12.2   47.4     35  
Utah            1203      4022   0.6        72.90     4.5   67.3    137  
Vermont          472      3907   0.6        71.64     5.5   57.1    168  
Virginia        4981      4701   1.4        70.08     9.5   47.8     85  
Washington      3559      4864   0.6        71.72     4.3   63.5     32  
West Virginia   1799      3617   1.4        69.48     6.7   41.6    100  
Wisconsin       4589      4468   0.7        72.48     3.0   54.5    149  
Wyoming          376      4566   0.6        70.29     6.9   62.9    173  
               Area  
Alabama         50708
Alaska         566432
Arizona        113417
Arkansas        51945
California     156361
Colorado       103766
Connecticut      4862
Delaware         1982
Florida         54090
Georgia         58073

In [28]:
USPersonalExpenditure

1940   1945   1950  1955 1960 
Food and Tobacco    22.200 44.500 59.60 73.2 86.80
Household Operation 10.500 15.500 29.00 36.5 46.20
Medical and Health   3.530  5.760  9.71 14.0 21.10
Personal Care        1.040  1.980  2.45  3.4  5.40
Private Education    0.341  0.974  1.80  2.6  3.64

In [1]:
# Mengetahui daftar built-in df
data()

In [5]:
head(state.x77) # 6 baris pertama

Population Income Illiteracy Life Exp Murder HS Grad Frost Area  
Alabama     3615      3624   2.1        69.05    15.1   41.3     20    50708
Alaska       365      6315   1.5        69.31    11.3   66.7    152   566432
Arizona     2212      4530   1.8        70.55     7.8   58.1     15   113417
Arkansas    2110      3378   1.9        70.66    10.1   39.9     65    51945
California 21198      5114   1.1        71.71    10.3   62.6     20   156361
Colorado    2541      4884   0.7        72.06     6.8   63.9    166   103766

In [6]:
tail(state.x77) # 6 baris terakhir

Population Income Illiteracy Life Exp Murder HS Grad Frost Area 
Vermont        472       3907   0.6        71.64    5.5    57.1    168    9267
Virginia      4981       4701   1.4        70.08    9.5    47.8     85   39780
Washington    3559       4864   0.6        71.72    4.3    63.5     32   66570
West Virginia 1799       3617   1.4        69.48    6.7    41.6    100   24070
Wisconsin     4589       4468   0.7        72.48    3.0    54.5    149   54464
Wyoming        376       4566   0.6        70.29    6.9    62.9    173   97203

In [7]:
str(state.x77) # struktur dari df

 num [1:50, 1:8] 3615 365 2212 2110 21198 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:50] "Alabama" "Alaska" "Arizona" "Arkansas" ...
  ..$ : chr [1:8] "Population" "Income" "Illiteracy" "Life Exp" ...


In [8]:
summary(state.x77) # sari statistik dari df berdasarkan kolom

   Population        Income       Illiteracy       Life Exp    
 Min.   :  365   Min.   :3098   Min.   :0.500   Min.   :67.96  
 1st Qu.: 1080   1st Qu.:3993   1st Qu.:0.625   1st Qu.:70.12  
 Median : 2838   Median :4519   Median :0.950   Median :70.67  
 Mean   : 4246   Mean   :4436   Mean   :1.170   Mean   :70.88  
 3rd Qu.: 4968   3rd Qu.:4814   3rd Qu.:1.575   3rd Qu.:71.89  
 Max.   :21198   Max.   :6315   Max.   :2.800   Max.   :73.60  
     Murder          HS Grad          Frost             Area       
 Min.   : 1.400   Min.   :37.80   Min.   :  0.00   Min.   :  1049  
 1st Qu.: 4.350   1st Qu.:48.05   1st Qu.: 66.25   1st Qu.: 36985  
 Median : 6.850   Median :53.25   Median :114.50   Median : 54277  
 Mean   : 7.378   Mean   :53.11   Mean   :104.46   Mean   : 70736  
 3rd Qu.:10.675   3rd Qu.:59.15   3rd Qu.:139.75   3rd Qu.: 81162  
 Max.   :15.100   Max.   :67.30   Max.   :188.00   Max.   :566432  

In [12]:
# mendefinisikan df
nama <- c('Agus', 'Sugio', 'Bayu', 'Atmo', 'Roy')
umur <- c(42,35,37,28,27)
kawin <- c(F,F,T,F,T)

In [13]:
data.frame(nama, umur, kawin)

nama  umur kawin
1 Agus  42   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE
4 Atmo  28   FALSE
5 Roy   27    TRUE

In [15]:
df <- data.frame(nama, umur, kawin)
df

nama  umur kawin
1 Agus  42   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE
4 Atmo  28   FALSE
5 Roy   27    TRUE

In [16]:
str(df)

'data.frame':	5 obs. of  3 variables:
 $ nama : Factor w/ 5 levels "Agus","Atmo",..: 1 5 3 2 4
 $ umur : num  42 35 37 28 27
 $ kawin: logi  FALSE FALSE TRUE FALSE TRUE


In [17]:
summary(df)

    nama        umur        kawin        
 Agus :1   Min.   :27.0   Mode :logical  
 Atmo :1   1st Qu.:28.0   FALSE:3        
 Bayu :1   Median :35.0   TRUE :2        
 Roy  :1   Mean   :33.8                  
 Sugio:1   3rd Qu.:37.0                  
           Max.   :42.0                  

## Seleksi dan pengindeksan Data Frame

In [18]:
df

nama  umur kawin
1 Agus  42   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE
4 Atmo  28   FALSE
5 Roy   27    TRUE

In [20]:
df[3, ] # ambil baris ketiga

nama umur kawin
3 Bayu 37   TRUE

In [24]:
df[,1]

[1] Agus  Sugio Bayu  Atmo  Roy  
Levels: Agus Atmo Bayu Roy Sugio

In [25]:
df[,'nama']

[1] Agus  Sugio Bayu  Atmo  Roy  
Levels: Agus Atmo Bayu Roy Sugio

In [26]:
df[1:4, c('nama', 'umur')]

nama  umur
1 Agus  42  
2 Sugio 35  
3 Bayu  37  
4 Atmo  28

In [27]:
df$umur

[1] 42 35 37 28 27

In [28]:
df[,'umur']

[1] 42 35 37 28 27

In [30]:
# fungsi subset
df

nama  umur kawin
1 Agus  42   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE
4 Atmo  28   FALSE
5 Roy   27    TRUE

In [31]:
subset(df,subset = kawin == T) 

nama umur kawin
3 Bayu 37   TRUE 
5 Roy  27   TRUE

In [32]:
subset(df, subset = umur > 30)

nama  umur kawin
1 Agus  42   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE

In [39]:
# Mengurutkan dataframe
urut.umur <- order(df['umur'])
urut.umur

[1] 5 4 2 3 1

In [41]:
df[urut.umur,]

nama  umur kawin
5 Roy   27    TRUE
4 Atmo  28   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE
1 Agus  42   FALSE

In [44]:
umur.terbalik <- order(-df['umur'])
umur.terbalik

[1] 1 3 2 4 5

In [46]:
df[umur.terbalik,]

nama  umur kawin
1 Agus  42   FALSE
3 Bayu  37    TRUE
2 Sugio 35   FALSE
4 Atmo  28   FALSE
5 Roy   27    TRUE

In [48]:
urut.umur <- order(df$umur)
df[urut.umur, ]

nama  umur kawin
5 Roy   27    TRUE
4 Atmo  28   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE
1 Agus  42   FALSE

## Operasi - operasi Data Frame

### Mendefinisikan data frame

### Mendapatkan info tentang data frame

### Referensi sel

### Referensi baris dan kolom