# Matriks

## Mendefinisikan matriks

In [1]:
b <- 1:10
b

[1]  1  2  3  4  5  6  7  8  9 10

In [2]:
matrix(b) # 10 x 1

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

In [3]:
matrix(b, nrow=2, ncol= 5) # by column

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [4]:
matrix(b, nrow=2, ncol= 5, byrow = T) # by row

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10

In [5]:
matrix(1:12, nrow = 4, byrow=TRUE) # 4 x 3 by row

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [6]:
# Mendefinisikan matriks dari vektor
fb <- c(250,255,260,263,265) # bayangkan sebagai harga saham
ms <- c(455,460,465,479, 470)

In [7]:
saham <- c(fb, ms)
saham

[1] 250 255 260 263 265 455 460 465 479 470

In [8]:
matriks.saham <- matrix(saham, nrow=2, byrow=T)
matriks.saham

[,1] [,2] [,3] [,4] [,5]
[1,] 250  255  260  263  265 
[2,] 455  460  465  479  470

In [9]:
# Menamakan baris dan kolom

In [10]:
hari <- c('sen', 'sel', 'rab', 'kam', 'jum')
perusahaan <- c('fb', 'ms')

In [11]:
colnames(matriks.saham) <- hari
rownames(matriks.saham) <- perusahaan

In [12]:
matriks.saham

sen sel rab kam jum
fb 250 255 260 263 265
ms 455 460 465 479 470

## Aritmatika matriks

In [13]:
mat <- matrix(1:25, nrow=5, byrow=T)
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [14]:
mat * mat # element-by-element

[,1] [,2] [,3] [,4] [,5]
[1,]   1    4    9   16   25 
[2,]  36   49   64   81  100 
[3,] 121  144  169  196  225 
[4,] 256  289  324  361  400 
[5,] 441  484  529  576  625

In [15]:
mat / mat

[,1] [,2] [,3] [,4] [,5]
[1,] 1    1    1    1    1   
[2,] 1    1    1    1    1   
[3,] 1    1    1    1    1   
[4,] 1    1    1    1    1   
[5,] 1    1    1    1    1

In [16]:
mat^2

[,1] [,2] [,3] [,4] [,5]
[1,]   1    4    9   16   25 
[2,]  36   49   64   81  100 
[3,] 121  144  169  196  225 
[4,] 256  289  324  361  400 
[5,] 441  484  529  576  625

In [17]:
1 / mat

[,1]       [,2]       [,3]       [,4]       [,5]      
[1,] 1.00000000 0.50000000 0.33333333 0.25000000 0.20000000
[2,] 0.16666667 0.14285714 0.12500000 0.11111111 0.10000000
[3,] 0.09090909 0.08333333 0.07692308 0.07142857 0.06666667
[4,] 0.06250000 0.05882353 0.05555556 0.05263158 0.05000000
[5,] 0.04761905 0.04545455 0.04347826 0.04166667 0.04000000

In [18]:
# Operator perbandingan di matriks

In [19]:
mat > 10

[,1]  [,2]  [,3]  [,4]  [,5] 
[1,] FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE
[3,]  TRUE  TRUE  TRUE  TRUE  TRUE
[4,]  TRUE  TRUE  TRUE  TRUE  TRUE
[5,]  TRUE  TRUE  TRUE  TRUE  TRUE

In [20]:
mat[mat > 10]

[1] 11 16 21 12 17 22 13 18 23 14 19 24 15 20 25

In [21]:
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [22]:
# Perkalian matriks
mat %*% mat

[,1] [,2] [,3] [,4] [,5]
[1,]  215  230  245  260  275
[2,]  490  530  570  610  650
[3,]  765  830  895  960 1025
[4,] 1040 1130 1220 1310 1400
[5,] 1315 1430 1545 1660 1775

## Operasi - operasi di matriks

In [23]:
# Mendefinisikan matriks dari vektor
fb <- c(250,255,260,263,265)
ms <- c(455,460,465,479, 470)
saham <- c(fb, ms)
matriks.saham <- matrix(saham, nrow=2, byrow=T)
colnames(matriks.saham) <- c('sen', 'sel', 'rab', 'kam', 'jum')
rownames(matriks.saham) <-  c('fb', 'ms')
matriks.saham

sen sel rab kam jum
fb 250 255 260 263 265
ms 455 460 465 479 470

In [24]:
colSums(matriks.saham) # penjumlahan pada kolom

sen sel rab kam jum 
705 715 725 742 735

In [25]:
rowSums(matriks.saham)

fb   ms 
1293 2329

In [26]:
rowMeans(matriks.saham)

fb    ms 
258.6 465.8

In [27]:
colMeans(matriks.saham)

sen   sel   rab   kam   jum 
352.5 357.5 362.5 371.0 367.5

In [28]:
# Menambahkan kolom dan baris ke matriks

In [29]:
google <- c(175,180,185,195,190)
saham.int <- rbind(matriks.saham, google)
saham.int

sen sel rab kam jum
fb     250 255 260 263 265
ms     455 460 465 479 470
google 175 180 185 195 190

In [30]:
# Menambahkan kolom ke matriks
rata2 <- rowMeans(saham.int)
rata2

fb     ms google 
 258.6  465.8  185.0

In [31]:
saham.int <- cbind(saham.int, rata2)
saham.int

sen sel rab kam jum rata2
fb     250 255 260 263 265 258.6
ms     455 460 465 479 470 465.8
google 175 180 185 195 190 185.0

## Seleksi dan pengindeksan matriks

In [32]:
v <- c(10,20,30,40,50)
v

[1] 10 20 30 40 50

In [33]:
v[3]

[1] 30

In [34]:
mat <- matrix(1:25, nrow=5, byrow=T)
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [35]:
mat[1,] # baris 1, seluruh kolom

[1] 1 2 3 4 5

In [36]:
mat[2,3]

[1] 8

In [37]:
mat[3,4]

[1] 14

In [38]:
mat[,3]

[1]  3  8 13 18 23

In [39]:
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [40]:
mat[,5]

[1]  5 10 15 20 25

In [41]:
mat[1:3,] # baris 1 sampai 3

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15

In [42]:
mat[,4:5] # kolom 4 hingga 5

[,1] [,2]
[1,]  4    5  
[2,]  9   10  
[3,] 14   15  
[4,] 19   20  
[5,] 24   25

In [43]:
mat[1:2, 1:3] # baris 1 sampai 2, kolom 1 sampai 3

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 6    7    8

In [44]:
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [45]:
mat[3:5, 3:5]

[,1] [,2] [,3]
[1,] 13   14   15  
[2,] 18   19   20  
[3,] 23   24   25

## Fungsi `factor()`

In [47]:
vek.warna <- c('merah', 'hijau', 'biru', 'merah', 'merah', 'hijau', 'biru')

In [48]:
vek.warna

[1] "merah" "hijau" "biru"  "merah" "merah" "hijau" "biru"

In [49]:
fact.warna <- factor(vek.warna, ordered=T, levels=c('merah', 'hijau', 'biru'))
fact.warna

[1] merah hijau biru  merah merah hijau biru 
Levels: merah < hijau < biru

In [50]:
summary(fact.warna)

merah hijau  biru 
    3     2     2

In [51]:
summary(vek.warna)

   Length     Class      Mode 
        7 character character 