# List

Kumpulan berbagai macam tipe data di R

In [1]:
v <- c(1,2,3,4,5)
M <- matrix(1:10, nrow=2)
c1 <- c('Ignatius', 'Laynez', 'Faber', 'Xaverius', 'Kanisius')
c2 <- c(42,37,28,45,43)

In [2]:
df <- data.frame(Nama = c1, ID = c2)
df

Nama     ID
1 Ignatius 42
2 Laynez   37
3 Faber    28
4 Xaverius 45
5 Kanisius 43

In [3]:
# Pendefinisian list
l <- list(v,M,df)
l

[[1]]
[1] 1 2 3 4 5

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[[3]]
      Nama ID
1 Ignatius 42
2   Laynez 37
3    Faber 28
4 Xaverius 45
5 Kanisius 43

In [4]:
# penamaaan ulang indeks list

l2 <- list(sampel_vektor = v, sampel_matriks = M, sample_data_frame = df)
l2

$sampel_vektor
[1] 1 2 3 4 5

$sampel_matriks
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_data_frame
      Nama ID
1 Ignatius 42
2   Laynez 37
3    Faber 28
4 Xaverius 45
5 Kanisius 43

In [5]:
l2[1]

$sampel_vektor
[1] 1 2 3 4 5

In [14]:
l2['sampel_vektor']

$sampel_vektor
[1] 1 2 3 4 5

In [8]:
l2$sampel_vektor

[1] 1 2 3 4 5

In [9]:
l2[['sampel_vektor']]

[1] 1 2 3 4 5

In [11]:
print(class(l2['sampel_vektor']))
print(class(l2[1]))

[1] "list"
[1] "list"


In [12]:
print(class(l2$sampel_vektor))
print(class(l2[['sampel_vektor']]))

[1] "numeric"
[1] "numeric"


In [15]:
# Mengombinasikan dua list
l3 <- c(l,l2)
l3

[[1]]
[1] 1 2 3 4 5

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[[3]]
      Nama ID
1 Ignatius 42
2   Laynez 37
3    Faber 28
4 Xaverius 45
5 Kanisius 43

$sampel_vektor
[1] 1 2 3 4 5

$sampel_matriks
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_data_frame
      Nama ID
1 Ignatius 42
2   Laynez 37
3    Faber 28
4 Xaverius 45
5 Kanisius 43

In [16]:
str(l2)

List of 3
 $ sampel_vektor    : num [1:5] 1 2 3 4 5
 $ sampel_matriks   : int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
 $ sample_data_frame:'data.frame':	5 obs. of  2 variables:
  ..$ Nama: Factor w/ 5 levels "Faber","Ignatius",..: 2 4 1 5 3
  ..$ ID  : num [1:5] 42 37 28 45 43


In [17]:
summary(l2)

                  Length Class      Mode   
sampel_vektor      5     -none-     numeric
sampel_matriks    10     -none-     numeric
sample_data_frame  2     data.frame list   